### ISSUE TITLE
it doesn't support multiple paths

### ISSUE THREAD

**Issue by dabowheel** [JS-DevTools/globify#1]
It doesn't support multiple paths such as this:
globify path1\*.js path2\*.js -o output.js

**Comment by JamesMessinger** [comment]
Good point.  It should definitely support that, since Browserify/Watchify support multiple paths.  I'll put this on my to-do list, but can't say for sure when I'll get to it, since I've got a lot of other stuff on my plate right now.  Feel free to submit a PR if you want
