### ISSUE TITLE
Excellent useful and helpful project

### ISSUE THREAD

**Issue by DevanB** [JS-DevTools/globify#12]
No issue here, I just wanted to praise you for creating globify! 

Been fighting using globs with npm scripts, browserify, and Windows. This project was the saving grace I've been trying to find for over 2 weeks.

While piping would be nice (so I can only use globify and not need to install watchify and browserify), I just wanted to thank you for the project and maintaining it!

**Comment by JamesMessinger** [comment]
awesome!  Thanks!   I should post notes like this on other OSS projects that I use and rely on every day.
