### ISSUE TITLE
Watch subclasses build main classes

### ISSUE THREAD

**Issue by Kiura** [JS-DevTools/globify#2]
Couldn't think of better title...
Here is an example of project structure:

``` javascript
lib/
 |__ cars.js
 |__ animals.js
 |__ classes/
       |__ dog.js
       |__ cat.js
       |__ volvo.js
       |__ porshe.js
```

currently it is only possible to watch main files and compile corresponding files...
e.g. if `globify 'lib/*.js' -w -v -o 'lib/out'` it will compile only when cars.js or animals.js is changed
is there any way to watch for all js in lib and compile cars.js and animals.js
or at least watch for all and compile all files?

**Comment by JamesMessinger** [comment]
Globify doesn't actually watch files itself.  In fact, it doesn't actually do _anything_ itself.  It's simply a pass-through to [`browserify`](https://www.npmjs.com/package/browserify) or [`watchify`](https://www.npmjs.com/package/watchify).  It passes along all of your parameters, expanding any globs as necessary.  All the actual work is done by browserify or watchify.

Watchify will automatically watch any files that are referenced via `require()` from your main entry files.  So, in your example, as long as the files in the `classes/` directory are referenced by `cars.js` and/or `animals.js`, then those files will be watched as well.  So if you make a change to `volvo.js`, for example, it will trigger a re-build.

**Comment by Kiura** [comment]
hmm, thats what I expected it to do, but in my case it doesn't work...

**Comment by JamesMessinger** [comment]
Try running watchify directly (without going through globify) and see if you get different behavior.   If you it still doesn't work, then it may be a bug in watchify.

**Comment by Kiura** [comment]
ok, I found the problem, and if anyone else is experiencing the same problem here is quote from watchify:

> It may be related to a bug in fsevents (see [#250](https://github.com/substack/watchify/issues/205#issuecomment-98672850) and [stackoverflow](http://stackoverflow.com/questions/26708205/webpack-watch-isnt-compiling-changed-files/28610124#28610124) ). Try the --poll flag and/or renaming the project's directory - that might help.

**Comment by JamesMessinger** [comment]
ok, cool.  Glad you figured it out.  But sucks that it's still an ongoing issue. :-/

**Comment by Kiura** [comment]
Indeed. Btw, Thx for pointing the right direction, spent hours trying to figure out the problem

**Comment by JamesMessinger** [comment]
:+1: np
