### ISSUE TITLE
Exclude from glob

### ISSUE THREAD

**Issue by franciscolourenco** [JS-DevTools/globify#5]
Is there a way to exclude certain patterns, like for example the node_modules directory? 
Maybe something in the lines of what bash supports? `**/*.coffee!(*node_modules*)`

**Comment by JamesMessinger** [comment]
See the `--exclude` arg: https://github.com/BigstickCarpet/globify#usage

**Comment by franciscolourenco** [comment]
Ops sorry about that, and once again, thank you :+1:

**Comment by franciscolourenco** [comment]
It doesn't seem to be working though.

```
globify -t coffeeify '**/*.coffee' -u '*node_modules*' --debug --outfile '*.js' --watch -v
```

I get a very big list of watchify commands being executed. Is it merely passing the options to browserify?

**Comment by JamesMessinger** [comment]
`*node_modules*` will only exclude files with "node_modules" in the name.  Use a globstar pattern, such as `node_modules/**` or `**/node_modules/**` to exclude everything beneath that folder

**Comment by franciscolourenco** [comment]
<3
