### ISSUE TITLE
Options -v -d

### ISSUE THREAD

**Issue by franciscolourenco** [JS-DevTools/globify#7]
These options appear in the a REAME example but doesn't seem to be any more information about them.

**Comment by franciscolourenco** [comment]
Ok, -d is --debug for source-maps, what about -v?

**Comment by JamesMessinger** [comment]
Are you talking about [here](https://github.com/BigstickCarpet/globify#watchify-transforms-other-options)?  That's just an example of specifying Browserify options.

**Comment by franciscolourenco** [comment]
Then -v is not documented in browserify?

**Comment by JamesMessinger** [comment]
I think that used to be an option in an older version of Browserify

**Comment by franciscolourenco** [comment]
What did it do?

**Comment by JamesMessinger** [comment]
dunno.  it's just an example, so I just picked a few random arguments from the Browserify README

**Comment by franciscolourenco** [comment]
Thanks the -v is the --verbose option for --watch
