### ISSUE TITLE
Uglifyjs support

### ISSUE THREAD

**Issue by franciscolourenco** [JS-DevTools/globify#8]
From the Ugligyfyify [docs](https://github.com/hughsk/uglifyify#motivationusage):

> "Uglifyify provides an additional optimization when used with Uglify, but does not provide all of the optimization that using Uglify on its own does, so it's not a replacement."

And indeed the bundle size resulting from uglifyify is bigger than the one produced by normal Uglifyjs2.
Is it possible to apply normal uglify with globify?

Related to https://github.com/BigstickCarpet/globify/issues/3

**Comment by JamesMessinger** [comment]
This isn't a globify question.  It's a browserify question.  All globify does is call browserify and pass-along the arguments that you give.  Globify has no control over which tools do or do-not work with browserify.
