### ISSUE TITLE
Support watchify pipe output option

### ISSUE THREAD

**Issue by Izhaki** [JS-DevTools/globify#9]
The [watchify docs](https://github.com/substack/watchify) say:

```
--outfile=FILE, -o FILE

This option is required. Write the browserify bundle to this file. If
the file contains the operators `|` or `>`, it will be treated as a
shell command, and the output will be piped to it.
```

Problem is that if you provide the outputfile something like the examples given

```
-o 'exorcist static/bundle.js.map > static/bundle.js'
```

globify does not recognise it as such and creates a folder instead.

**Comment by JamesMessinger** [comment]
This is related to Issue #11, since supporting output to stdout would also support piping to other programs.
